// This file is auto-generated by @hey-api/openapi-ts

import { AxiosError } from "axios";

export type ErrorTaggedUnion<T extends Record<string, unknown>> = {
  [K in keyof T]: {
    error: T[K];
    status: K;
  };
};

export const handleAxiosError = <T extends Record<string, unknown>>(
  error: AxiosError,
): ErrorTaggedUnion<T> => {
  return {
    status: error.status,
    error: error.response?.data,
  } as ErrorTaggedUnion<T>;
};
