// This file is auto-generated by @hey-api/openapi-ts

import {
  listUsers,
  createUser,
  deleteUser,
  getUserById,
  updateUser,
  getUserPosts,
  createPost,
} from "./sdk.gen";

/**
 * List users
 * Retrieve a list of users with optional filtering
 */
export const listUsersToolOptions = {
  name: "listUsers",
  description: "Retrieve a list of users with optional filtering",
  execute: listUsers,
};

/**
 * Create user
 * Create a new user
 */
export const createUserToolOptions = {
  name: "createUser",
  description: "Create a new user",
  execute: createUser,
  needsApproval: true,
};

/**
 * Delete user
 * Delete a user by ID
 */
export const deleteUserToolOptions = {
  name: "deleteUser",
  description: "Delete a user by ID",
  execute: deleteUser,
  needsApproval: true,
};

/**
 * Get user by ID
 * Retrieve a specific user by their ID
 */
export const getUserByIdToolOptions = {
  name: "getUserById",
  description: "Retrieve a specific user by their ID",
  execute: getUserById,
};

/**
 * Update user
 * Update an existing user
 */
export const updateUserToolOptions = {
  name: "updateUser",
  description: "Update an existing user",
  execute: updateUser,
  needsApproval: true,
};

/**
 * Get user posts
 * Retrieve all posts for a specific user
 */
export const getUserPostsToolOptions = {
  name: "getUserPosts",
  description: "Retrieve all posts for a specific user",
  execute: getUserPosts,
};

/**
 * Create post
 * Create a new post
 */
export const createPostToolOptions = {
  name: "createPost",
  description: "Create a new post",
  execute: createPost,
  needsApproval: true,
};
