// This file is auto-generated by @hey-api/openapi-ts

import {
  listUsers,
  createUser,
  deleteUser,
  getUserById,
  updateUser,
  getUserPosts,
  createPost,
} from "./sdk.gen";
import { tool } from "@openai/agents";
import {
  zListUsersData,
  zCreateUserData,
  zDeleteUserData,
  zGetUserByIdData,
  zUpdateUserData,
  zGetUserPostsData,
  zCreatePostData,
} from "./zod.gen";

/**
 * List users
 * Retrieve a list of users with optional filtering
 */
export const listUsersToolOptions = {
  name: "listUsers",
  description: "Retrieve a list of users with optional filtering",
  parameters: zListUsersData,
  execute: listUsers,
};

export const listUsersTool = tool(listUsersToolOptions);

/**
 * Create user
 * Create a new user
 */
export const createUserToolOptions = {
  name: "createUser",
  description: "Create a new user",
  parameters: zCreateUserData,
  execute: createUser,
  needsApproval: true,
};

export const createUserTool = tool(createUserToolOptions);

/**
 * Delete user
 * Delete a user by ID
 */
export const deleteUserToolOptions = {
  name: "deleteUser",
  description: "Delete a user by ID",
  parameters: zDeleteUserData,
  execute: deleteUser,
  needsApproval: true,
};

export const deleteUserTool = tool(deleteUserToolOptions);

/**
 * Get user by ID
 * Retrieve a specific user by their ID
 */
export const getUserByIdToolOptions = {
  name: "getUserById",
  description: "Retrieve a specific user by their ID",
  parameters: zGetUserByIdData,
  execute: getUserById,
};

export const getUserByIdTool = tool(getUserByIdToolOptions);

/**
 * Update user
 * Update an existing user
 */
export const updateUserToolOptions = {
  name: "updateUser",
  description: "Update an existing user",
  parameters: zUpdateUserData,
  execute: updateUser,
  needsApproval: true,
};

export const updateUserTool = tool(updateUserToolOptions);

/**
 * Get user posts
 * Retrieve all posts for a specific user
 */
export const getUserPostsToolOptions = {
  name: "getUserPosts",
  description: "Retrieve all posts for a specific user",
  parameters: zGetUserPostsData,
  execute: getUserPosts,
};

export const getUserPostsTool = tool(getUserPostsToolOptions);

/**
 * Create post
 * Create a new post
 */
export const createPostToolOptions = {
  name: "createPost",
  description: "Create a new post",
  parameters: zCreatePostData,
  execute: createPost,
  needsApproval: true,
};

export const createPostTool = tool(createPostToolOptions);
