// This file is auto-generated by @hey-api/openapi-ts

import {
  listUsers,
  createUser,
  deleteUser,
  getUserById,
  updateUser,
  getUserPosts,
  createPost,
} from "./sdk.gen";
import {
  zListUsersData,
  zCreateUserData,
  zDeleteUserData,
  zGetUserByIdData,
  zUpdateUserData,
  zGetUserPostsData,
  zCreatePostData,
} from "./zod.gen";

export const listUsersTool =
  /**
   * List users
   * Retrieve a list of users with optional filtering
   */
  {
    name: "listUsers",
    description: "Retrieve a list of users with optional filtering",
    parameters: zListUsersData,
    exec: listUsers,
  };

export const createUserTool =
  /**
   * Create user
   * Create a new user
   */
  {
    name: "createUser",
    description: "Create a new user",
    parameters: zCreateUserData,
    exec: createUser,
  };

export const deleteUserTool =
  /**
   * Delete user
   * Delete a user by ID
   */
  {
    name: "deleteUser",
    description: "Delete a user by ID",
    parameters: zDeleteUserData,
    exec: deleteUser,
  };

export const getUserByIdTool =
  /**
   * Get user by ID
   * Retrieve a specific user by their ID
   */
  {
    name: "getUserById",
    description: "Retrieve a specific user by their ID",
    parameters: zGetUserByIdData,
    exec: getUserById,
  };

export const updateUserTool =
  /**
   * Update user
   * Update an existing user
   */
  {
    name: "updateUser",
    description: "Update an existing user",
    parameters: zUpdateUserData,
    exec: updateUser,
  };

export const getUserPostsTool =
  /**
   * Get user posts
   * Retrieve all posts for a specific user
   */
  {
    name: "getUserPosts",
    description: "Retrieve all posts for a specific user",
    parameters: zGetUserPostsData,
    exec: getUserPosts,
  };

export const createPostTool =
  /**
   * Create post
   * Create a new post
   */
  {
    name: "createPost",
    description: "Create a new post",
    parameters: zCreatePostData,
    exec: createPost,
  };
