// This file is auto-generated by @hey-api/openapi-ts

import {
  listUsers,
  type Options,
  createUser,
  deleteUser,
  getUserById,
  updateUser,
  getUserPosts,
  createPost,
} from './sdk.gen';
import { ResultAsync } from 'neverthrow';
import type {
  ListUsersData,
  ListUsersErrors,
  CreateUserData,
  CreateUserErrors,
  DeleteUserData,
  DeleteUserErrors,
  GetUserByIdData,
  GetUserByIdErrors,
  UpdateUserData,
  UpdateUserErrors,
  GetUserPostsData,
  GetUserPostsErrors,
  CreatePostData,
} from './types.gen';

export const listUsersSafe = (options: Options<ListUsersData, true>) => {
  return ResultAsync.fromPromise(
    listUsers(options),
    (error) => error as ListUsersErrors,
  );
};

export const createUserSafe = (options: Options<CreateUserData, true>) => {
  return ResultAsync.fromPromise(
    createUser(options),
    (error) => error as CreateUserErrors,
  );
};

export const deleteUserSafe = (options: Options<DeleteUserData, true>) => {
  return ResultAsync.fromPromise(
    deleteUser(options),
    (error) => error as DeleteUserErrors,
  );
};

export const getUserByIdSafe = (options: Options<GetUserByIdData, true>) => {
  return ResultAsync.fromPromise(
    getUserById(options),
    (error) => error as GetUserByIdErrors,
  );
};

export const updateUserSafe = (options: Options<UpdateUserData, true>) => {
  return ResultAsync.fromPromise(
    updateUser(options),
    (error) => error as UpdateUserErrors,
  );
};

export const getUserPostsSafe = (options: Options<GetUserPostsData, true>) => {
  return ResultAsync.fromPromise(
    getUserPosts(options),
    (error) => error as GetUserPostsErrors,
  );
};

export const createPostSafe = (options: Options<CreatePostData, true>) => {
  return ResultAsync.fromPromise(
    createPost(options),
    (error) => error as unknown,
  );
};
